const fs = require('node:fs')
const path = require('node:path')
const crypto = require('node:crypto')
const {createRequire} = require('node:module')
const {root,target} = require('./locations.cjs')
const sharp = createRequire(path.join(root,'package.json'))('sharp')
const catalog = require('./catalog-raw.json')
const vectors = require('./vectors.json')
const write = (file, data) => { const dest=path.join(target,file);fs.mkdirSync(path.dirname(dest),{recursive:true});fs.writeFileSync(dest,JSON.stringify(data)) }
const formulaPattern = /\\\(([\s\S]*?)\\\)|\\\[([\s\S]*?)\\\]|\$\$([\s\S]*?)\$\$|\$([^$\n]+)\$/g
async function main(){
  for(const name of ['math-permutations-combinations','math-derivatives']){
    await sharp(path.join(root,'packages/web/public/illustrations/topics',name+'-v3.png'))
      .resize({width:660,withoutEnlargement:true}).webp({quality:85}).toFile(path.join(target,'static/plaza',name+'.webp'))
  }
  const formulas = new Map()
  const entries = []
  const publicEntries = []
  for(const p of catalog){
    let figure
    if(p.figure?.imagePath){
      const src=path.join(root,'packages/web/public',p.figure.imagePath)
      if(!fs.existsSync(src))throw Error('Missing question figure '+src)
      const dest=`static/catalog-questions/${p.id}.png`
      fs.mkdirSync(path.dirname(path.join(target,dest)),{recursive:true})
      await sharp(src).resize({width:900,withoutEnlargement:true}).png({palette:true}).toFile(path.join(target,dest))
      figure={...p.figure,imagePath:'/'+dest}
    }
    const entry={id:p.id,webId:p.webId,title:p.title,subject:p.subject,statement:p.statement,
      overview:p.overview,problemType:p.subject==='chemistry'?'有机物结构与官能团':p.problemType,givens:p.givens,target:p.target,answer:p.answer,figure,
      equilibrium:p.equilibrium,
      steps:p.steps.map(({svg,...s})=>({...s,scene:s.scene.dimension===2
        ?{dimension:2,center:s.scene.center,radius:s.scene.radius,camera:s.scene.camera,operations:vectors[p.id+'/'+s.id]}
        :s.scene}))}
    const content=[entry.statement,entry.overview,entry.answer,...entry.givens,...entry.target,
      ...entry.steps.flatMap(s=>[s.title,s.summary,s.detail,s.formula,s.caption,...s.expect])]
    for(const text of content){
      if(typeof text!=='string')continue
      for(const match of text.matchAll(formulaPattern)){
        const key=match[0],latex=match[1]??match[2]??match[3]??match[4]
        // A worksheet preset contains an unexpanded ${bs} escape. Keep its
        // source text for auditing, but render the intended LaTeX backslash.
        if(!formulas.has(key))formulas.set(key,{key,latex:latex.replaceAll('${bs}','\\'),id:crypto.createHash('sha1').update(key).digest('hex').slice(0,12)})
      }
    }
    entries.push(entry)
    const subject=p.subject
    const artwork=p.topicIllustrationId ?? (subject==='physics'?'physics-force-analysis':subject==='chemistry'?'chemistry-ethanol':subject==='worksheet'?'worksheet-quadratic':'math-functions')
    publicEntries.push({id:p.id,webId:p.webId,title:p.title,excerpt:p.excerpt,subject,subjectLabel:p.subjectLabel,
      grade:p.grade,difficulty:p.difficulty,durationMinutes:parseInt(p.duration)||5,
      accent:subject==='physics'?'#E8793D':subject==='chemistry'?'#D85D75':subject==='worksheet'?'#2B9F88':'#3974E8',
      visual:subject==='physics'?'force':subject==='chemistry'?'molecule':subject==='worksheet'?'worksheet':artwork==='math-solid-geometry'?'geometry':'function',
      artwork,thumbnailPath:figure?.imagePath,featured:p.featured??false,stepCount:p.steps.length})
  }
  // Share SVG styles and keep the payload compact even in HBuilder debug
  // builds (Vite's JSON-to-object transform otherwise expands it past 2 MB).
  const styles=[],styleIds=new Map()
  const styleKeys=['matrix','fill','stroke','fillOpacity','strokeOpacity','opacity','width','cap','join','dash','nonScaling','font','fontSize','fontFamily','fontWeight','fontStyle','anchor','baseline','paintOrder']
  for(const p of entries)for(const s of p.steps)if(s.scene.dimension===2){
    s.scene.operations=s.scene.operations.map(op=>{
      const style={},geometry={}
      for(const [key,value] of Object.entries(op))(styleKeys.includes(key)?style:geometry)[key]=value
      const key=JSON.stringify(style)
      if(!styleIds.has(key)){styleIds.set(key,styles.length);styles.push(style)}
      return {...geometry,styleRef:styleIds.get(key)}
    })
    require('node:assert/strict').deepEqual(s.scene.operations.map(({styleRef,...geometry})=>({...styles[styleRef],...geometry})),vectors[p.id+'/'+s.id],`Vector style roundtrip changed ${p.id}/${s.id}`)
  }
  write('data/web-problems.json',publicEntries)
  write('subpackages/catalog/data/problems.json',entries)
  write('subpackages/catalog/data/vector-styles.json',styles)
  fs.writeFileSync(path.join(target,'subpackages/catalog/data/solution-payload.ts'),
    '// Generated by scripts/web-catalog/package-catalog.cjs. Keep as a compact string in debug builds.\nexport default JSON.parse('+JSON.stringify(JSON.stringify(entries))+')\n')
  write('subpackages/catalog/data/tokens.json',require('./web-tokens.json'))
  write('subpackages/catalog/data/source-manifest.json',{problems:entries.length,steps:entries.reduce((n,p)=>n+p.steps.length,0),
    entries:entries.map(p=>({id:p.id,webId:p.webId,steps:p.steps.map(s=>({id:s.id,title:s.title,pageId:s.pageId,dimension:s.scene.dimension}))}))})
  const webRequire=createRequire(path.join(root,'packages/web/package.json'))
  const katex=webRequire('katex')
  const css=require('node:url').pathToFileURL(webRequire.resolve('katex/dist/katex.min.css')).href
  fs.writeFileSync(path.join(__dirname,'formulas.json'),JSON.stringify([...formulas.values()]))
  fs.writeFileSync(path.join(__dirname,'formulas.html'),'<!doctype html><meta charset="utf-8"><link rel="stylesheet" href="'+css+'"><style>body{margin:0;color:#173252}.row{padding:4px;width:max-content}.formula{display:inline-block;font-size:32px;padding:4px;white-space:nowrap}.katex{font-size:1em}</style>'+
    [...formulas.values()].map(f=>'<div class="row"><span class="formula" id="m'+f.id+'">'+katex.renderToString(f.latex,{throwOnError:true,strict:false,displayMode:false})+'</span></div>').join(''))
  console.log(JSON.stringify({problems:entries.length,steps:entries.reduce((n,p)=>n+p.steps.length,0),formulas:formulas.size,
    dataBytes:fs.statSync(path.join(target,'subpackages/catalog/data/problems.json')).size}))
}
main().catch(e=>{console.error(e);process.exitCode=1})
